POST http://localhost:3003/api/blogs
Content-Type: application/json 

{
    "title": "Full Stack Open",
    "author": "Popcorn Patty",
    "url": "randomurl.com",
    "likes": 15

}


###
GET http://localhost:3003/api/blogs
