POST http://localhost:3003/api/blogs
Content-Type: application/json 

{
    "title": "TDD harms architecture",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
    "likes": 0
}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/643e3a40477e0827812e5ec0

###
PUT http://localhost:3003/api/blogs/643e3dadedd87ca6f9fb33e8 
Content-Type: application/json 

{
    "title": "TDD harms architecture",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
    "likes": 55
}